### ISSUE TITLE
restructure files

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#19]
I have some proposals regarding the project directory structure:
* delete the compiled js files from specs folder
* move rules to separate subfolder
* and maybe move specs to specs folder where they usually are. What is the reason why they are in the source folder? Did You ran into problems of configuring typescript? If so, I could offer some help. Or is it because You wanted to keep rule and test close to each other, so when a rule without test is added, it would stand out in the folder view?

**Comment by MeirionHughes** [comment]
To be honest this is my second TS project and the example I saw had it done like this. I suppose logically it was because you had "source" files that compile to outputs before being run.   

I do like how doing is the current way give me the real-actual intelisense for the require imports. i.e. if you edit the rule, you can see the correct intelisense in VS Code, without the need to compile manually.  

I suppose I could have the spec ts files in the spec folder, and during the compile replace the `...from './source/file'` to `'./dist/file'`

**Comment by atsu85** [comment]
Thanks for the response.

> I do like how doing is the current way give me the real-actual intelisense for the require imports. i.e. if you edit the rule, you can see the correct intelisense in VS Code, without the need to compile manually. 

I totally agree, intelisense is a must have for me as well, but I don't understand how which suggestion would break it?

**Comment by MeirionHughes** [comment]
It should be okay I guess to do ts->js in the spec folder. I already have to "fix" the import paths anyway.

**Comment by MeirionHughes** [comment]
Right I think this a little better at least. all the `*.spec.ts` files are now in `/spec` they will compile, test and clean up. Also have it so you can add a breakpoint on the spec ts files, press f5 and it VS will break on it.

**Comment by atsu85** [comment]
What do You think about this suggestion:
> move rules to separate subfolder
